---
devices:
  srl1:
    hostname: "172.20.20.2"
    platform: "nokia_srl"
    username: "admin"
    password: "NokiaSrl1!"
    expected:
      hostname_pattern: "^SRL[0-9]+-[A-Z]{2,4}$"
      ntp_server: "10.0.0.1"
      network_instances: ["DATA", "VOICE", "MGMT-VRF"]
      interfaces_up:
        - "ethernet-1/1"
        - "ethernet-1/2"
      ping_targets:
        - "10.0.12.2"
        - "10.0.13.2"

  srl2:
    hostname: "172.20.20.3"
    platform: "nokia_srl"
    username: "admin"
    password: "NokiaSrl1!"
    expected:
      hostname_pattern: "^SRL[0-9]+-[A-Z]{2,4}$"
      ntp_server: "10.0.0.1"
      network_instances: ["DATA", "VOICE", "MGMT-VRF"]
      interfaces_up:
        - "ethernet-1/1"
        - "ethernet-1/2"
      ping_targets:
        - "10.0.12.1"
        - "10.0.24.2"

  srl3:
    hostname: "172.20.20.4"
    platform: "nokia_srl"
    username: "admin"
    password: "NokiaSrl1!"
    expected:
      hostname_pattern: "^LEAF[0-9]+-[A-Z]{2,4}$"
      ntp_server: "10.0.0.1"
      network_instances: ["DATA", "VOICE", "MGMT-VRF"]
      interfaces_up:
        - "ethernet-1/1"
        - "ethernet-1/2"
      ping_targets:
        - "10.0.13.1"
        - "10.0.24.1"
